services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: westbrand-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - westbrand-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  pgdb:
    image: pgvector/pgvector:pg17
    container_name: westbrand-db
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - westbrand-network

volumes:
  redis_data:
  pgdata:

networks:
  westbrand-network:
    driver: bridge
